yev/task#40
AstraVlad/sportclubs pull request #13
Opened 2023-01-20 11:50 UTC by YevBor

2023-01-20 21:20 UTC, Miskamyasa commented on SportClubsBackend/src/routes/forgot.ts
> +
нет задуманного ответа в задаче. Должен ответить ок и сообщение. У тебя роут повиснет без ответа

2023-01-20 21:20 UTC, Miskamyasa requested changes

2023-01-20 21:20 UTC, Miskamyasa commented on SportClubsBackend/src/routes/forgot.ts
> +
тут

2023-01-21 19:52 UTC, YevBor commented on SportClubsBackend/src/routes/forgot.ts
> +
По ошибке залил недоделаный код.
Походу нужно проверять что заливаю . Вобщем я добавил статус и меседж

2023-01-21 20:45 UTC, Miskamyasa commented on SportClubsBackend/src/routes/forgot.ts
> +
Да, когда реквест создаешь, хороший тон, сразу пробежать его самому. Поверь, очень много увидишь и захочешь долить

2023-01-21 20:46 UTC, Miskamyasa approved these changes
огонь!

2023-01-21 21:04 UTC, merged